export const Actions = {
  OPEN_TAB: 'OPEN_TAB',
  CLEAR_DELIVERY_INFO: 'CLEAR_DELIVERY_INFO',
  
  SET_FIRST_NAME: 'SET_FIRST_NAME',
  SET_LAST_NAME: 'SET_LAST_NAME',
  SET_PHONE: 'SET_PHONE',
  SET_EMAIL: 'SET_EMAIL',
}