export const Actions = {
  OPEN_TAB: 'OPEN_TAB',
  CLEAR_DELIVERY_INFO: 'CLEAR_DELIVERY_INFO',
  
  SET_FIRST_NAME: 'SET_FIRST_NAME',
  SET_LAST_NAME: 'SET_LAST_NAME',
  SET_PHONE: 'SET_PHONE',
  SET_EMAIL: 'SET_EMAIL',

  SET_IS_PICKUP: 'SET_IS_PICKUP', 
  SET_COUNTRY: 'SET_COUNTRY',
  SET_CITY: 'SET_CITY',
  SET_INDEX: 'SET_INDEX',
  SET_ADDRESS: 'SET_ADDRESS',
  SET_DATE: 'SET_DATE',
  SET_COMMENT: 'SET_COMMENT'
}